hangmangame/hangman/urls.py
from django.urls import path

from .views import (
  GameDetailView,
  MainView,
  StartGameView,
  GameFinishedView,
  MakeGuessAjaxView,
  UpdateTimeRemainingAjaxView,
  StatisticsDetailView
)

app_name = 'hangman'
urlpatterns = [
    path('', MainView.as_view(), name='main_page'),
    path('start-game/', StartGameView.as_view(), name='start_game'),
    path('<int:id>/hanging/', GameDetailView.as_view(), name='play_game'),
    path('ajax/make-guess/', MakeGuessAjaxView.as_view(), name='make_guess'),
    path('ajax/update-time-remaining/', UpdateTimeRemainingAjaxView.as_view(), name='update_time'),
    path('<int:id>/game-over/', GameFinishedView.as_view(), name='game_over'),
    path('stats/', StatisticsDetailView.as_view(), name='stats')
]

hangmangame/hangmangame/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profiles.urls')),
    path('', include('hangman.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

hangmangame/profiles/urls.py
from django.urls import path, reverse_lazy

from django.contrib.auth.views import LogoutView, PasswordResetConfirmView, PasswordResetCompleteView

from .views import (
    CustomLoginView,
    CustomSignUpView,
    CustomResetPasswordView,
    ProfileUpdateView,
    ProfileDetailView,
)

app_name = 'profiles'
urlpatterns = [
    path('<int:id>/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('<int:id>/detail/', ProfileDetailView.as_view(), name='profile_detail'),
    path('signup/', CustomSignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('hangman:main_page')),  name='logout'),
    path('accounts/password-reset/', CustomResetPasswordView.as_view(), name='password_reset'),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', \
        PasswordResetConfirmView.as_view(template_name='profiles/password_reset_confirm.html', success_url=reverse_lazy('profiles:password_reset_complete')), \
        name='password_reset_confirm'),
    path('accounts/password-reset-complete/', \
        PasswordResetCompleteView.as_view(template_name='profiles/password_reset_complete.html'), \
        name='password_reset_complete'),
]

hangmangame/profiles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    created_by = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    f_name = models.CharField(max_length=100)
    l_name = models.CharField(max_length=100)
    image = models.ImageField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.f_name + ' ' + self.l_name

hangmangame/profiles/forms.py
from django import forms
from .models import (
  Profile
)

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.auth import login, authenticate

class UserRegisterForm(UserCreationForm):
  class Meta:
    model = User
    fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

  def __init__(self, request, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.request = request

    self.fields['username'].widget = forms.TextInput(attrs={
        'id': 'username_field_register',
        'class': 'inputs',
        'name': 'username',
        'placeholder': 'Enter your username'})

    self.fields['email'].widget = forms.TextInput(attrs={
        'id': 'email_field_register',
        'class': 'inputs',
        'name': 'email',
        'placeholder': 'Enter your email'})

    self.fields['first_name'].widget = forms.TextInput(attrs={
        'id': 'first_name_field_register',
        'class': 'inputs',
        'name': 'first_name',
        'placeholder': 'Enter your first name'})

    self.fields['last_name'].widget = forms.TextInput(attrs={
        'id': 'last_name_field_register',
        'class': 'inputs',
        'name': 'last_name',
        'placeholder': 'Enter your last name'})

    self.fields['password1'].widget = forms.TextInput(attrs={
        'id': 'password1_field_register',
        'class': 'inputs',
        'name': 'password1',
        'placeholder': 'Enter your password',
        'type': 'password'})

    self.fields['password2'].widget = forms.TextInput(attrs={
        'id': 'password2_field_register',
        'class': 'inputs',
        'name': 'password2',
        'placeholder': 'Confirm your password',
        'type': 'password'})

  def save(self, commit=True):
    user = super().save(commit=commit)
    if commit:
        auth_user = authenticate(
            username=self.cleaned_data['username'], 
            password=self.cleaned_data['password1']
        )
        login(self.request, auth_user)

    return user

  def clean(self):
    cleaned_data = super().clean()
    email = cleaned_data.get('email')
    try:
      user = User.objects.get(email=email)
      self.add_error('email', "A profile with this email already exists.")
    except (User.DoesNotExist):
      return cleaned_data
class UserLoginForm(AuthenticationForm):
  class Meta:
    model = User
    fields = ['username', 'password']

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['username'].widget = forms.TextInput(attrs={
        'id': 'username_field',
        'class': 'inputs',
        'name': 'username',
        'placeholder': 'Enter your username'})

    self.fields['password'].widget = forms.TextInput(attrs={
        'id': 'password_field',
        'class': 'inputs',
        'name': 'password',
        'placeholder': 'Enter your password',
        'type': 'password'})

class ProfileModelForm(forms.ModelForm):
  class Meta:
    model = Profile
    fields = [
        'image',
        'f_name',
        'l_name',
    ]

    labels = {
      'image': 'Picture',
      'f_name': 'First name',
      'l_name': 'Last name',
    }

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)

    self.fields['image'].required = False

  def clean(self):
    clean_data = super().clean()
    if 'clear-image' in list(self.data.keys()):
      clean_data['clear_image'] = True
    return clean_data

hangmangame/profiles/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponse
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
    TemplateView,
    FormView
)

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import (
    PasswordResetView,
)

from django.contrib.auth import login, authenticate

from django.core.exceptions import PermissionDenied

from .models import (
  Profile,
)

from .forms import (
    ProfileModelForm,
    UserLoginForm,
    UserRegisterForm
)

# Create your views here.
class AjaxableResponseMixin(object):
    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.is_ajax():
            data = {
                'id': self.object.id,
            }
            return JsonResponse(data)
        else:
            return response

class CustomLoginView(SuccessMessageMixin, FormView):
    template_name = 'profiles/login.html'
    form_class = UserLoginForm
    success_message = 'You have successfully logged in'

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request=self.request, username=username, password=password)
        if user:
            login(self.request, user)
        return super().form_valid(form)

    def form_invalid(self, form):
        return JsonResponse({'status': 'Wrong username or password'}, status=400)

    def get_success_url(self):
        return reverse_lazy('hangman:main_page')


class CustomSignUpView(SuccessMessageMixin, AjaxableResponseMixin, CreateView):
    template_name = 'profiles/register.html'
    form_class = UserRegisterForm
    success_message = 'Your profile was created successfully'
    success_url = reverse_lazy('hangman:main_page')

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(created_by=user, f_name=user.first_name, l_name=user.last_name)
        return super().form_valid(form)
    
    def form_invalid(self, form):
        return JsonResponse({'status': form.errors}, status=400)

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        form_kwargs['request'] = self.request
        return form_kwargs

class CustomResetPasswordView(SuccessMessageMixin, AjaxableResponseMixin, PasswordResetView):
    template_name = 'profiles/password_reset.html'
    email_template_name = 'profiles/password_reset_email.html'
    subject_template_name = 'profiles/password_reset_subject.txt'
    success_message = "We've emailed you instructions for setting up your password, " \
                      "if an account exists with the email you entered, you should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you had registered with, and check your spam folder."
    success_url = reverse_lazy('hangman:main_page')


class ProfileUpdateView(LoginRequiredMixin, AjaxableResponseMixin, UpdateView):
    template_name = 'profiles/profile_update.html'
    form_class = ProfileModelForm

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Profile, id=id_)

    def form_valid(self, form):
        data = form.cleaned_data
        self.object = form.save(commit=False)
        if data.get('clear_image'):
            self.object.image = None
        self.object.save()
        return JsonResponse({'update': 'done'}, status=200)

    def dispatch(self, request, *args, **kwargs):
        object = Profile.objects.get(id=self.kwargs.get('id'))
        if request.user.profile != object:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

class ProfileDetailView(LoginRequiredMixin, AjaxableResponseMixin, DetailView):
    template_name = 'profiles/profile_detail.html'
    model = Profile

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Profile, id=id_)

hangmangame/profiles/templates/profiles/base.html
<!DOCTYPE html>
<html>
  <head>
    {% block styles %}
    {% endblock %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8= sha256-T+aPohYXbm0fRYDpJLr+zJ9RmYTswGsahAoIsNiMld4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
    <title>{% block title %} Hangman {% endblock %}</title>

  </head>

  <body>

    {% block navbar %}
    {% endblock navbar%}

    {% if messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        {% for message in messages %}
          <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        {% endfor %}
      </div>
    {% endif %}

    {% block content %} 
    {% endblock %} 

    {% block js %} 
    {% endblock %}

  </body>
</html>

hangmangame/profiles/templates/profiles/login.html
{% load crispy_forms_tags %}

<div id="id-container-form" class="container-form">
    <form id="id-login-form" action="{% url 'profiles:login' %}" method='POST'>{% csrf_token %}
        {{form|crispy}}
        <input id="id-submit-button" type='submit' class='btn btn-success' value='Login'/>
        <button class="btn btn-secondary"><a id="id-password-reset" href="{% url 'profiles:password_reset' %}">Forgot password!</a></button>
    </form>
</div>

<style>
    .btn {
        margin-top: 5px;
        margin-bottom: 5px;
    }

    #id-password-reset {
        text-decoration: none;
        color: white;
    }
</style>

hangmangame/profiles/templates/profiles/password_reset.html
{% extends "profiles/base.html" %}

{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
  </div>
{% endblock content %}

hangmangame/profiles/templates/profiles/password_reset_complete.html
{% extends "profiles/base.html" %}

{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'hangman:main_page' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

hangmangame/profiles/templates/profiles/password_reset_confirm.html
{% extends "profiles/base.html" %}

{% block title %} 
    Password Reset 
{% endblock title%}

{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if validlink %}
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Reset Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Reset Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% else %}
                    <div class="alert alert-warning">
                        The password reset link was invalid, possibly because it has already been used.
                        Please request a new password reset.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

hangmangame/profiles/templates/profiles/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} HangPerson Account, click the link below:

  {{ protocol }}://{{ domain }}{% url 'profiles:password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead.

  Sincerely,
  The HangPerson Team
{% endautoescape %}

hangmangame/profiles/templates/profiles/profile_detail.html
<div class="media">
    {% if object.image %}
        <img src="{{ object.image.url }}" class="mr-3" width="60" height="80" alt="...">
    {% endif %}
    <div class="media-body">
        <h5 class="mt-0">{{ object.created_by.username }}</h5>
        Name: {{ object.f_name }} <br>
        Surname: {{ object.l_name }}
    </div>
    <button class="btn btn-info"><a id="id-profile-update-button" style="text-decoration: none; color: white;" href="{% url 'profiles:profile_update' id=object.id %}">Update</a></button>
</div>

<style>
    .mr-3 {
        margin-right: 5px !important;
    }
</style>

hangmangame/profiles/templates/profiles/profile_update.html
{% load crispy_forms_tags %}
<form id="id-profile-update-form" action="{% url 'profiles:profile_update' id=object.id %}" enctype="multipart/form-data"> {% csrf_token %}
    <div class="photo">
        {{form.image|as_crispy_field}}
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="clear-image" id="inlineRadio1" value="option1">
            <label class="form-check-label" for="inlineRadio1">Clear Image</label>
        </div>
    </div>

    <div class="f-name">
        {{form.f_name|as_crispy_field}}
    </div>

    <div class="l-name">
        {{form.l_name|as_crispy_field}}
    </div>

    <input id="id-profile-update-submit-button" type='submit' class='btn btn-success' value='Save'/>
    <button id="id-profile-update-cancel" class="btn btn-secondary">Cancel</button>
</form>

<style>
    .photo, .f-name, .l-name {
        margin-bottom: 3px;
    }

    .control-label {
        margin-bottom: 0px;
        font-weight: 500;
    }
</style>

hangmangame/profiles/templates/profiles/register.html
{% load crispy_forms_tags %}

<div id="id-container-form" class="container-form">
    <form id="id-register-form" action="{% url 'profiles:signup' %}" method='POST'>{% csrf_token %}
        {{form|crispy}}
        <input id="id-submit-button" type='submit' class='btn btn-success' value='Register'/>
    </form>
</div>

<style>
    .btn {
        margin-top: 5px;
        margin-bottom: 5px;
    }
</style>