hangmangame/hangman/urls.py
from django.urls import path

from .views import (
  GameDetailView,
  MainView,
  StartGameView,
  GameFinishedView,
  MakeGuessAjaxView,
  UpdateTimeRemainingAjaxView,
  StatisticsDetailView
)

app_name = 'hangman'
urlpatterns = [
    path('', MainView.as_view(), name='main_page'),
    path('start-game/', StartGameView.as_view(), name='start_game'),
    path('<int:id>/hanging/', GameDetailView.as_view(), name='play_game'),
    path('ajax/make-guess/', MakeGuessAjaxView.as_view(), name='make_guess'),
    path('ajax/update-time-remaining/', UpdateTimeRemainingAjaxView.as_view(), name='update_time'),
    path('<int:id>/game-over/', GameFinishedView.as_view(), name='game_over'),
    path('stats/', StatisticsDetailView.as_view(), name='stats')
]

hangmangame/hangmangame/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profiles.urls')),
    path('', include('hangman.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

hangmangame/profiles/urls.py
from django.urls import path, reverse_lazy

from django.contrib.auth.views import LogoutView, PasswordResetConfirmView, PasswordResetCompleteView

from .views import (
    CustomLoginView,
    CustomSignUpView,
    CustomResetPasswordView,
    ProfileUpdateView,
    ProfileDetailView,
)

app_name = 'profiles'
urlpatterns = [
    path('<int:id>/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('<int:id>/detail/', ProfileDetailView.as_view(), name='profile_detail'),
    path('signup/', CustomSignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('hangman:main_page')),  name='logout'),
    path('accounts/password-reset/', CustomResetPasswordView.as_view(), name='password_reset'),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', \
        PasswordResetConfirmView.as_view(template_name='profiles/password_reset_confirm.html', success_url=reverse_lazy('profiles:password_reset_complete')), \
        name='password_reset_confirm'),
    path('accounts/password-reset-complete/', \
        PasswordResetCompleteView.as_view(template_name='profiles/password_reset_complete.html'), \
        name='password_reset_complete'),
]

hangmangame/hangman/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class HangmanWord(models.Model):
    hard = 'H'
    medium = 'M'
    easy = 'E'
    DIFFICULTY_CHOICES = (
        (hard, 'HARD'),
        (medium, 'MEDIUM'),
        (easy, 'EASY')
    )

    word = models.CharField(max_length=100)
    difficulty = models.CharField(max_length=1, choices=DIFFICULTY_CHOICES)

    def __str__(self):
        return self.word

    def save(self, *args, **kwargs):
        self.difficulty = self.calc_word_difficulty()
        super().save(*args, **kwargs)

    def calc_word_difficulty(self):
        # calc word score
        score = len(self.word) + len(set(self.word))
        if score > 15:
            return self.hard
        elif score > 10:
            return self.medium
        else:
            return self.easy

class HangmanGame(models.Model):
    WIN = 'W'
    LOSS = 'L'
    RESULT_CHOICES = (
        (WIN, 'WON'),
        (LOSS, 'LOST')
    )
    player = models.ForeignKey("profiles.Profile", on_delete=models.CASCADE, related_name='games', null=True)
    guess_word = models.CharField(max_length=100)
    time_allowed = models.DurationField(null=True)
    guesses_allowed = models.IntegerField(default=6, validators=[
        MaxValueValidator(6),
        MinValueValidator(1)
    ])
    started_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    result = models.CharField(max_length=1, choices=RESULT_CHOICES, null=True)
    guessed_letters = models.CharField(max_length=26, default='')

    def __str__(self):
        return self.guess_word

    def get_guess_word_difficulty(self):
        score = len(self.guess_word) + len(set(self.guess_word))
        if score > 15:
            return 'H'
        elif score > 10:
            return 'M'
        else:
            return 'E'

    def get_absolute_url(self):
        return reverse('hangman:play_game', kwargs={'id': self.id})
    

hangmangame/hangman/forms.py
from django import forms

from .models import HangmanGame, HangmanWord

from .widgets import SplitDurationWidget

import re
class HangmanGameModelForm(forms.ModelForm):
    user_provided = 'U'
    db_provided = 'D'
    WORD_SOURCES = (
        (user_provided, 'USER'),
        (db_provided, 'RANDOM')
    )
    word_source = forms.ChoiceField(
        label='Word Source',
        initial=db_provided, 
        choices=WORD_SOURCES, 
        widget=forms.Select(),
        required=True
    )

    word_difficulty = forms.ChoiceField(
        label='Word Difficulty',
        initial=HangmanWord.easy,
        choices=HangmanWord.DIFFICULTY_CHOICES,
        widget=forms.Select(),
        required=False
    )
    class Meta:
        model = HangmanGame
        fields = [
            'guess_word',
            'time_allowed',
            'guesses_allowed'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['word_difficulty'].widget.attrs['id'] = 'id-word_difficulty_field'
        self.fields['word_difficulty'].widget.attrs['class'] = 'word_difficulty_field'
        self.fields['word_difficulty'].widget.attrs['name'] = 'word_difficulty'

        self.fields['word_source'].widget.attrs['id'] = 'id-word_source_field'
        self.fields['word_source'].widget.attrs['class'] = 'word_source_field'
        self.fields['word_source'].widget.attrs['name'] = 'word_source'

        self.fields['guess_word'].widget = forms.TextInput(attrs={
            'id': 'id-guess_word-field',
            'class': 'guess_word-field',
            'name': 'guess_word',
            'placeholder': 'Enter a word'})
        self.fields['guess_word'].required = False

        self.fields['time_allowed'].widget = SplitDurationWidget(attrs={
            'type': 'text',
            'id': 'id-time_allowed-field',
            'class': 'time_allowed-field',
            'name': 'time_allowed'})
        self.fields['time_allowed'].required = False
        self.fields['time_allowed'].help_text = 'Leave blank if unlimited'

        self.fields['guesses_allowed'].widget.attrs['id'] = 'id-guesses_allowed-field'
        self.fields['guesses_allowed'].widget.attrs['class'] = 'guesses_allowed-field'
        self.fields['guesses_allowed'].widget.attrs['name'] = 'guesses_allowed'
        self.fields['guesses_allowed'].widget.attrs['placeholder'] = 'Leave blank if unlimited'
        self.fields['guesses_allowed'].required = False
    
    def clean_guess_word(self):
        word = self.data.get('guess_word').lower()
        pattern = re.search("[^A-Za-z\s]", word)
        if pattern:
            raise forms.ValidationError("Word can only include ASCII characters.")

    def clean_time_allowed(self):
        h = self.data.get('time_allowed_hours') if self.data.get('time_allowed_hours') != '' else 0
        m = self.data.get('time_allowed_minutes') if self.data.get('time_allowed_minutes') != '' else 0
        s = self.data.get('time_allowed_seconds') if self.data.get('time_allowed_seconds') != '' else 0
        try:
            if any([int(i) < 0 for i in [h, m, s]]):
                raise forms.ValidationError("Duration cannot be negative.")
        except (ValueError):
            raise forms.ValidationError("Please input integers only.")
        return '{}:{}:{}'.format(h, m, s)

hangmangame/hangman/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.http import JsonResponse, HttpResponse
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
    TemplateView,
    FormView,
    View
)

from django.views.generic.base import ContextMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages

from django.core.exceptions import PermissionDenied

from .forms import HangmanGameModelForm
from .models import HangmanGame, HangmanWord
from .utils import (
    get_current_status,
    is_finished, 
    get_available_letters, 
    classify_guessed_letters, 
    update_guesses_remaining,
    serve_correct_image
)

from random import randint
import datetime
from profiles.models import Profile

# Create your views here.
class AjaxableResponseMixin(object):
    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.is_ajax():
            data = {
                'id': self.object.id,
                'url': reverse('hangman:play_game', kwargs={'id': self.object.id})
            }
            return JsonResponse(data)
        else:
            return response

class MainView(TemplateView):
    template_name = 'hangman/main_page.html'

    # def render_to_response(self, context, **response_kwargs):
    #     """ Allow AJAX requests to be handled more gracefully """
    #     if self.request.is_ajax():
    #         unfinished_games = HangmanGame.objects.filter(player=self.request.user.profile).filter(result__isnull=True)
    #         durations = [game.time_allowed for game in unfinished_games]
    #         return JsonResponse({'durations': durations}, status=200, content_type='application/json', **response_kwargs)
    #     else:
    #         return super().render_to_response(context, **response_kwargs)

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.is_ajax():
                # context = self.get_context_data()
                unfinished_games = HangmanGame.objects.filter(player=self.request.user.profile).filter(result__isnull=True)
                durations = [game.time_allowed.total_seconds() * 1000 if game.time_allowed is not None else None for game in unfinished_games]
                ids = [game.id for game in unfinished_games]
                # print(durations)
                # return render(request, self.template_name, context)
                return JsonResponse({'durations': durations, 'ids': ids}, status=200, content_type='application/json')
            else:
                context = self.get_context_data()
                return render(request, self.template_name, context)
        else:
            # context = self.get_context_data()
            return render(request, self.template_name, {})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            unfinished_games = HangmanGame.objects.filter(player=self.request.user.profile).filter(result__isnull=True).order_by('-updated_date')
            context['unfinished_games'] = unfinished_games
            statuses = [get_current_status(game.guessed_letters, game.guess_word) for game in unfinished_games]
            context['statuses'] = statuses
            ids = [game.id for game in unfinished_games]
            context['ids'] = ids
        except (Profile.DoesNotExist, AttributeError):
            pass
        return context

class StartGameView(LoginRequiredMixin, AjaxableResponseMixin, CreateView):
    template_name = 'hangman/start_game.html'
    model = HangmanGame
    form_class = HangmanGameModelForm

    def post(self, *args, **kwargs):
        self.object = None
        return super().post(self.request, *args, **kwargs)

    def form_valid(self, form):
        if form.cleaned_data['word_source'] == 'D':
            count = HangmanWord.objects.filter(difficulty=form.cleaned_data['word_difficulty']).count()
            word = HangmanWord.objects.filter(difficulty=form.cleaned_data['word_difficulty'])[randint(0, count - 1)]
            form.instance.guess_word = word
        form.instance.player = self.request.user.profile
        return super().form_valid(form)

class MakeGuessAjaxView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        obj = HangmanGame.objects.get(id=request.POST.get('id'))
        letter_guessed = request.POST.get('letter')
        all_guessed_letters = obj.guessed_letters
        if letter_guessed not in all_guessed_letters:
            all_guessed_letters += letter_guessed
            guesses_remaining = update_guesses_remaining(obj.guesses_allowed, obj.guess_word, letter_guessed)

            obj.guessed_letters = all_guessed_letters
            obj.guesses_allowed = guesses_remaining
            obj.save()

            is_game_finished, is_won = is_finished(obj.guessed_letters, obj.guess_word, obj.guesses_allowed)
            if is_game_finished:
                if is_won:
                    obj.result = HangmanGame.WIN
                else:
                    obj.result = HangmanGame.LOSS
                obj.save()

            current_status = get_current_status(obj.guessed_letters, obj.guess_word)
            hit, miss = classify_guessed_letters(obj.guessed_letters, obj.guess_word)
            image = serve_correct_image(obj.guesses_allowed)

            return JsonResponse({
                'hits': hit,
                'misses': miss,
                'is_game_finished': is_game_finished,
                'current_status': current_status,
                'guesses_remaining': guesses_remaining,
                'image': image
            }, status=200, content_type='application/json')
        else:
            return JsonResponse({'error': 'You already guessed this letter'}, status=400, content_type='application/json')

class UpdateTimeRemainingAjaxView(LoginRequiredMixin, View):
    # def post(self, request, *args, **kwargs):
    #     obj = HangmanGame.objects.get(id=request.POST.get('id'))
    #     time_remaining = request.POST.get('time_remaining')
    #     time_remaining_formatted = datetime.timedelta(milliseconds=int(time_remaining))
    #     obj.time_allowed = time_remaining_formatted
    #     obj.save()
    #     return JsonResponse({'saving': 'Done'}, status=200, content_type='application/json')
    def post(self, request, *args, **kwargs):
        # print(request.POST)
        for id_ in request.POST.keys():
            obj = HangmanGame.objects.get(id=int(id_))
            obj.time_allowed = datetime.timedelta(milliseconds=int(request.POST.get(id_)))
            obj.save()
        # for key, value in request.POST.items():
        #     obj = HangmanGame.objects.get(id=int(request.POST.getlist(key)))

        # object_list = [HangmanGame.objects.get(id=int(id_)) for id_ in request.POST.keys()]
        # time_remaining_list = []
        # for index, obj in enumerate(object_list):
        #     time_remaining_formatted = datetime.timedelta(milliseconds=int(time_remaining_list[index]))
        #     obj.time_allowed = time_remaining_formatted
        #     obj.save()
        return JsonResponse({'saving': 'Done'}, status=200, content_type='application/json')

class StatisticsDetailView(LoginRequiredMixin, TemplateView):
    template_name = 'hangman/game_statistics.html'

    def calc_total_score(self, wins, losses):
        """Score logic takes into account word length, number of unique letters in a word, guesses remaining, duration remaining"""
        logic_dict = {
            'word_length': 2,
            'num_of_uniq_letters': 3,
            'guesses_remaining': 5,
            'time_remaining': 1
        }
        total_score = 0
        for win in wins:
            word = win.guess_word.replace(' ', '')
            time_remaining = win.time_allowed.total_seconds() if win.time_allowed is not None else 0
            total_score += len(word) * logic_dict['word_length'] + \
                            len(set(word)) * logic_dict['num_of_uniq_letters'] + \
                            win.guesses_allowed * logic_dict['guesses_remaining'] + \
                            time_remaining / 60 * logic_dict['time_remaining']

        for loss in losses:
            if loss.get_guess_word_difficulty() == 'H':
                total_score -= 20
            elif loss.get_guess_word_difficulty() == 'M':
                total_score -= 15
            else:
                total_score -= 10

        return total_score if total_score >= 0 else 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        wins = HangmanGame.objects.filter(player=self.request.user.profile).filter(result='W')
        losses = HangmanGame.objects.filter(player=self.request.user.profile).filter(result='L')
        context['wins'] = wins
        context['losses'] = losses
        context['wh'] = len([win for win in wins if win.get_guess_word_difficulty() == 'H'])
        context['wm'] = len([win for win in wins if win.get_guess_word_difficulty() == 'M'])
        context['we'] = len([win for win in wins if win.get_guess_word_difficulty() == 'E'])
        context['lh'] = len([loss for loss in losses if loss.get_guess_word_difficulty() == 'H'])
        context['lm'] = len([loss for loss in losses if loss.get_guess_word_difficulty() == 'M'])
        context['le'] = len([loss for loss in losses if loss.get_guess_word_difficulty() == 'E'])
        context['total'] = self.calc_total_score(wins, losses)
        return context

class GameDetailView(LoginRequiredMixin, DetailView):

hangmangame/hangman/templates/hangman/base.html
<!DOCTYPE html>
<html>
  <head>
    {% block styles %}
    {% endblock %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8= sha256-T+aPohYXbm0fRYDpJLr+zJ9RmYTswGsahAoIsNiMld4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
    <title>{% block title %} Hangman {% endblock %}</title>

    <link rel="shortcut icon" href="#">

  </head>

  <body>

    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <a class="navbar-brand" href="{% url 'hangman:main_page' %}"> HangPerson </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" id="id-start-game-button" start-game-form-url="{% url 'hangman:start_game' %}"> Start a Game </a>
                    </li>
                    <div id="id-start-game-form-fields" class="start-game-form-fields" style="display: none;"></div>

                    <li class="nav-item">
                        <a class="nav-link" id="id-statistics-button" stats-url="{% url 'hangman:stats' %}"> Statistics </a>
                    </li>
                    <div id="id-stats-fields" class="stats-fields" style="display: none;"></div>

                    <li class="nav-item" style="float:right">
                        <a class="nav-link" id="id-profile-button" href="{% url 'profiles:profile_detail' id=request.user.profile.id %}"> Welcome {{request.user.username}} </a>
                    </li>
                    <div id="id-profile-fields" class="profile-fields" style="display: none;"></div>

                    <li class="nav-item" style="float:right">
                        <a class="nav-link" href="{% url 'profiles:logout' %}"> Logout </a>
                    </li>
                {% else %}
                    <li class="nav-item" style="float:right">
                        <a class="nav-link" id="id-login-button" login-form-url="{% url 'profiles:login' %}"> Login </a>
                    </li>
                    <div id="id-login-form-fields" class="login-form-fields" style="display: none;"></div>

                    <li class="nav-item">
                        <a class="nav-link" id="id-register-button" register-form-url="{% url 'profiles:signup' %}"> Sign Up </a>
                    </li>
                    <div id="id-register-form-fields" class="register-form-fields" style="display: none;"></div>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% endblock navbar%}

    {% if messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <div class="messages">
            {% for message in messages %}
              <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %}

    {% block content %} 
    {% endblock %} 

    {% block js %} 
    {% endblock %}

  </body>
</html>

hangmangame/hangman/templates/hangman/main_page.html
{% extends "hangman/base.html" %} 

{% load crispy_forms_tags %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'hangman/main_page.css' %}">
{% endblock styles %}
{% block js %}
    <script src="{% static 'profiles/profile_ops.js' %}"></script>
    <script src="{% static 'hangman/success_message.js' %}"></script>
    <script src="{% static 'hangman/render_forms.js' %}"></script>
    <script src="{% static 'hangman/render_stats.js' %}"></script>
    <script src="{% static 'hangman/start_game_form.js' %}"></script>
    <script src="{% static 'hangman/main_page.js' %}"></script>
{% endblock js %}

{% block content %}
    <div class="jumbotron" style="background-color: lightblue;">
        <h1 class="display-4">Welcome to the HangPerson Game!</h1>
        <p class="lead">Please don't let our person hang!</p>
        <hr class="my-4">
        <ul>
            <li>Either play against a randomly chosen word from our stores or bring a friend and choose the word yourselves</li>
            <li>You can either make it a race against the time, or have all the time in the world</li>
            <li>You cannot have more than 6 guesses per game, unfortunately, our Person doesn't have that many limbs</li>
        </ul>
    </div>

    {% load get_item %}

    {% csrf_token %}

    {% if request.user.is_authenticated %}

        <div class="spinner">
            <div class="d-flex justify-content-center">
                <div class="spinner-border" role="status">
                <span class="sr-only">Loading...</span>
                </div>
            </div>
        </div>

        <div class="row" style="display: none;" id="id-games" data-id="{{ids}}" update-time-remaining-url="{% url 'hangman:update_time' %}" style="margin-left: 10px;">
            {% for game in unfinished_games %}
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title"> Current status: <span style="word-spacing: 15px; letter-spacing: 5px;"> {{statuses|index:forloop.counter0|upper}} </span> </h5>
                            <p class="card-text">Guesses remaining: {{game.guesses_allowed}} </p>
                            {% comment %} <p class="card-text">Time remaining: {{game.time_allowed}} </p> {% endcomment %}
                            <p id="id-time-remaining-{{game.id}}" data-id="{{game.time_allowed}}" class="card-text">Time remaining: <span id="id-time-{{game.id}}"> {{game.time_allowed}} </span> </p>
                            <a href="{% url 'hangman:play_game' id=game.id %}" class="btn btn-primary">Continue Playing!</a>
                        </div>
                    </div>
                </div>
            {% empty %}
            {% endfor %}
        </div>
    
    {% endif %}
{% endblock content %}

hangmangame/hangman/templates/hangman/play_game.html
{% extends 'hangman/base.html' %}

{% load static %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'hangman/play_game.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hangman/main_page.css' %}">
{% endblock styles %}
{% block js %}
    <script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
    <script src="{% static 'profiles/profile_ops.js' %}"></script>
    <script src="{% static 'hangman/countdown.js' %}"></script>
    <script src="{% static 'hangman/play_game.js' %}"></script>
    <script src="{% static 'hangman/render_forms.js' %}"></script>
    <script src="{% static 'hangman/render_stats.js' %}"></script>
    <script src="{% static 'hangman/start_game_form.js' %}"></script>
{% endblock js %}

{% block title %}
    Don't Let The Man Hanging!
{% endblock title %}

{% block content %}
<a id="id-game-over" href="{% url 'hangman:game_over' id=object.id %}"></a>
{% comment %} <a id="id-play-game" href="{% url 'hangman:play_game' id=object.id %}"></a> {% endcomment %}
    <div class="main">
        <div class="left">
            <h2 id="id-word-status" style="font-size: 60px; word-spacing: 30px; letter-spacing: 5px;"> {{ current_status|upper }} </h2>

            {% comment %} <div class="buttons">
                <button class="btn btn-info" id="id-timer" data-time-allowed="{{object.time_allowed}}">Start Timer!</button>
                <button class="btn btn-danger" id="id-reset-timer">Restart Timer!</button>
            </div> {% endcomment %}

            {% comment %} <button class="btn btn-info" id="id-start-timer">Start Clock</button> {% endcomment %}
            {% if object.time_allowed %}
                <button class="btn btn-warning" object-id="{{object.id}}" update-time-url="{% url 'hangman:update_time' %}" id="id-timer" data-time-allowed="{{object.time_allowed}}"> <a id="id-clock"></a> </button>
                <button class="btn btn-danger" id="id-reset-timer">Restart Clock</button>
                <p id="countdown"> </p>
            {% endif %}

            <p style="font-size: 22px;"> <u> Available letters: </u> </p>
            {% for letter in available_letters %}
                {% csrf_token %}
                <button class="btn btn-primary" object-id="{{object.id}}" make-guess-url="{% url 'hangman:make_guess' %}" id="{{letter}}" style="font-size: 16px;"> {{letter|upper}} </button>
            {% empty %}
            {% endfor %}

            <p id="id-used-letters" style="font-size: 22px;"> <u> Used letters: </u> </p>
            <div id="id-ajax"></div>

            {% if not is_finished.0 %}
                <div id="id-used-letters-on-refresh">
                    {% for hit in hits %}
                        <button class="btn btn-success"> {{hit|upper}} </button>
                    {% empty %}
                    {% endfor %}

                    {% for miss in misses %}
                        <button class="btn btn-danger"> {{miss|upper}} </button>
                    {% empty %}
                    {% endfor %}
                </div>
            {% endif %}
{% comment %}             <div class="save-buttons" style="margin-top: 15px;">
                <button class="btn btn-info" id="id-save">Save Current Status</button>
                <button class="btn btn-info" id="id-save-and-exit" exit-url="{% url 'hangman:main_page' %}">Save Current Status and Go to Main Page</button>
            </div> {% endcomment %}
        </div>
        <div class="right"> 
            <h1> Save the Person From Hanging! </h1>
            <p id="id-guess-remaining" remaining-guesses="{{object.guesses_allowed}}"> Guesses remaining: {{object.guesses_allowed}} </p>
            <img id="id-hangman-status-1" src="{% static 'hangman/1.jpg' %}" alt="My image" style="display: none;">
            <img id="id-hangman-status-2" src="{% static 'hangman/2.jpg' %}" alt="My image" style="display: none;">
            <img id="id-hangman-status-3" src="{% static 'hangman/3.jpg' %}" alt="My image" style="display: none;">
            <img id="id-hangman-status-4" src="{% static 'hangman/4.jpg' %}" alt="My image" style="display: none;">
            <img id="id-hangman-status-5" src="{% static 'hangman/5.jpg' %}" alt="My image" style="display: none;">
            <img id="id-hangman-status-6" src="{% static 'hangman/6.jpg' %}" alt="My image" style="display: none;">
            <img id="id-hangman-status-7" src="{% static 'hangman/7.jpg' %}" alt="My image" style="display: none;">
        </div>
    </div>
{% endblock content %}